### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by SimeonStoykovQC**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SimeonStoykovQC** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
Last time I checked, Ansible playbooks cannot be executed on Windows hosts (but they can be used to provision Windows machines).

Has this changed?

**Comment by mariusvniekerk** [comment]
You probably need to define an entrypoint to get the ansible batch test to pass

**Comment by xhochy** [comment]
> You probably need to define an entrypoint to get the ansible batch test to pass

@SimeonStoykovQC You should get these entrypoints by regnerating the recipe using https://github.com/conda-incubator/grayskull

**Comment by tschoonj** [comment]
This PR should really be closed. You cannot run Ansible on Windows. See [here](https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows)

**Comment by xhochy** [comment]
> This PR should really be closed. You cannot run Ansible on Windows. See [here](https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows)

Damn.

**Pull request closed without merging**
