### PR TITLE
Bump version to 2.4.0.0

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
@conda-forge-admin, please rerender

**Comment by souravsingh** [comment]
The Windows build is failing citing ``The filename or extension is too long``

**Comment by brainstorm** [comment]
@souravsingh To be honest, I think that we can skip the windows build for now, would you mind adding that skip? I.e [like I did for iperf](https://github.com/conda-forge/iperf-feedstock/blob/master/recipe/meta.yaml#L16)?

Thanks!

**Comment by mariusvniekerk** [comment]
We might also want to start building py3 versions for this library since ansible is supporting 3 these days

**Comment by cjw296** [comment]
Hey guys, anything I can do to help here? See #5 for my reason for interest...

**Pull request closed without merging**
